const gistsMock = [
    {
        "url": "https://api.github.com/gists/6cad326836d38bd3a7ae",
        "forks_url": "https://api.github.com/gists/6cad326836d38bd3a7ae/forks",
        "commits_url": "https://api.github.com/gists/6cad326836d38bd3a7ae/commits",
        "id": "6cad326836d38bd3a7ae",
        "node_id": "MDQ6R2lzdDZjYWQzMjY4MzZkMzhiZDNhN2Fl",
        "git_pull_url": "https://gist.github.com/6cad326836d38bd3a7ae.git",
        "git_push_url": "https://gist.github.com/6cad326836d38bd3a7ae.git",
        "html_url": "https://gist.github.com/6cad326836d38bd3a7ae",
        "files": {
            "hello_world.rb": {
                "filename": "hello_world.rb",
                "type": "application/x-ruby",
                "language": "Ruby",
                "raw_url": "https://gist.githubusercontent.com/octocat/6cad326836d38bd3a7ae/raw/db9c55113504e46fa076e7df3a04ce592e2e86d8/hello_world.rb",
                "size": 175
            }
        },
        "public": true,
        "created_at": "2014-10-01T16:19:34Z",
        "updated_at": "2021-01-17T17:47:15Z",
        "description": "Hello world!",
        "comments": 258,
        "user": null,
        "comments_url": "https://api.github.com/gists/6cad326836d38bd3a7ae/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/0831f3fbd83ac4d46451",
        "forks_url": "https://api.github.com/gists/0831f3fbd83ac4d46451/forks",
        "commits_url": "https://api.github.com/gists/0831f3fbd83ac4d46451/commits",
        "id": "0831f3fbd83ac4d46451",
        "node_id": "MDQ6R2lzdDA4MzFmM2ZiZDgzYWM0ZDQ2NDUx",
        "git_pull_url": "https://gist.github.com/0831f3fbd83ac4d46451.git",
        "git_push_url": "https://gist.github.com/0831f3fbd83ac4d46451.git",
        "html_url": "https://gist.github.com/0831f3fbd83ac4d46451",
        "files": {
            "git-author-rewrite.sh": {
                "filename": "git-author-rewrite.sh",
                "type": "application/x-sh",
                "language": "Shell",
                "raw_url": "https://gist.githubusercontent.com/octocat/0831f3fbd83ac4d46451/raw/db76e0abc9cca660de31ffd2e0b2da2e7821417a/git-author-rewrite.sh",
                "size": 494
            }
        },
        "public": true,
        "created_at": "2014-07-23T23:15:04Z",
        "updated_at": "2021-01-17T17:47:23Z",
        "description": "",
        "comments": 15,
        "user": null,
        "comments_url": "https://api.github.com/gists/0831f3fbd83ac4d46451/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/2a6851cde24cdaf4b85b",
        "forks_url": "https://api.github.com/gists/2a6851cde24cdaf4b85b/forks",
        "commits_url": "https://api.github.com/gists/2a6851cde24cdaf4b85b/commits",
        "id": "2a6851cde24cdaf4b85b",
        "node_id": "MDQ6R2lzdDJhNjg1MWNkZTI0Y2RhZjRiODVi",
        "git_pull_url": "https://gist.github.com/2a6851cde24cdaf4b85b.git",
        "git_push_url": "https://gist.github.com/2a6851cde24cdaf4b85b.git",
        "html_url": "https://gist.github.com/2a6851cde24cdaf4b85b",
        "files": {
            "ssh_key_add.sh": {
                "filename": "ssh_key_add.sh",
                "type": "application/x-sh",
                "language": "Shell",
                "raw_url": "https://gist.githubusercontent.com/octocat/2a6851cde24cdaf4b85b/raw/262294097f4852ec26a0019ad7e34d692be1328d/ssh_key_add.sh",
                "size": 1317
            }
        },
        "public": true,
        "created_at": "2014-07-03T19:33:02Z",
        "updated_at": "2021-01-17T17:48:13Z",
        "description": "",
        "comments": 1,
        "user": null,
        "comments_url": "https://api.github.com/gists/2a6851cde24cdaf4b85b/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/9257657",
        "forks_url": "https://api.github.com/gists/9257657/forks",
        "commits_url": "https://api.github.com/gists/9257657/commits",
        "id": "9257657",
        "node_id": "MDQ6R2lzdDkyNTc2NTc=",
        "git_pull_url": "https://gist.github.com/9257657.git",
        "git_push_url": "https://gist.github.com/9257657.git",
        "html_url": "https://gist.github.com/9257657",
        "files": {
            ".gitignore": {
                "filename": ".gitignore",
                "type": "text/plain",
                "language": "Ignore List",
                "raw_url": "https://gist.githubusercontent.com/octocat/9257657/raw/c91b435be351fcdff00f6f97f20824d0286b99ef/.gitignore",
                "size": 443
            }
        },
        "public": true,
        "created_at": "2014-02-27T19:38:27Z",
        "updated_at": "2021-01-19T07:12:36Z",
        "description": "Some common .gitignore configurations",
        "comments": 139,
        "user": null,
        "comments_url": "https://api.github.com/gists/9257657/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/1305321",
        "forks_url": "https://api.github.com/gists/1305321/forks",
        "commits_url": "https://api.github.com/gists/1305321/commits",
        "id": "1305321",
        "node_id": "MDQ6R2lzdDEzMDUzMjE=",
        "git_pull_url": "https://gist.github.com/1305321.git",
        "git_push_url": "https://gist.github.com/1305321.git",
        "html_url": "https://gist.github.com/1305321",
        "files": {
            "test.cs": {
                "filename": "test.cs",
                "type": "text/plain",
                "language": "C#",
                "raw_url": "https://gist.githubusercontent.com/octocat/1305321/raw/57aa0172cb4a580ebaece3ec793e10599cb957c6/test.cs",
                "size": 303
            }
        },
        "public": true,
        "created_at": "2011-10-22T00:18:47Z",
        "updated_at": "2021-01-17T17:48:52Z",
        "description": null,
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/1305321/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/1169854",
        "forks_url": "https://api.github.com/gists/1169854/forks",
        "commits_url": "https://api.github.com/gists/1169854/commits",
        "id": "1169854",
        "node_id": "MDQ6R2lzdDExNjk4NTQ=",
        "git_pull_url": "https://gist.github.com/1169854.git",
        "git_push_url": "https://gist.github.com/1169854.git",
        "html_url": "https://gist.github.com/1169854",
        "files": {
            "test.cs": {
                "filename": "test.cs",
                "type": "text/plain",
                "language": "C#",
                "raw_url": "https://gist.githubusercontent.com/octocat/1169854/raw/09754c5f1c8d1c4e92bd8b77dfd1ef085152f71e/test.cs",
                "size": 7252
            }
        },
        "public": true,
        "created_at": "2011-08-25T02:45:38Z",
        "updated_at": "2015-09-26T22:37:54Z",
        "description": null,
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/1169854/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/1169852",
        "forks_url": "https://api.github.com/gists/1169852/forks",
        "commits_url": "https://api.github.com/gists/1169852/commits",
        "id": "1169852",
        "node_id": "MDQ6R2lzdDExNjk4NTI=",
        "git_pull_url": "https://gist.github.com/1169852.git",
        "git_push_url": "https://gist.github.com/1169852.git",
        "html_url": "https://gist.github.com/1169852",
        "files": {
            "test.cs": {
                "filename": "test.cs",
                "type": "text/plain",
                "language": "C#",
                "raw_url": "https://gist.githubusercontent.com/octocat/1169852/raw/c3dbb09bfaad34e0a3d81f13902ec5f11b86831d/test.cs",
                "size": 536
            }
        },
        "public": true,
        "created_at": "2011-08-25T02:43:53Z",
        "updated_at": "2021-01-17T17:49:22Z",
        "description": null,
        "comments": 3,
        "user": null,
        "comments_url": "https://api.github.com/gists/1169852/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    },
    {
        "url": "https://api.github.com/gists/1162032",
        "forks_url": "https://api.github.com/gists/1162032/forks",
        "commits_url": "https://api.github.com/gists/1162032/commits",
        "id": "1162032",
        "node_id": "MDQ6R2lzdDExNjIwMzI=",
        "git_pull_url": "https://gist.github.com/1162032.git",
        "git_push_url": "https://gist.github.com/1162032.git",
        "html_url": "https://gist.github.com/1162032",
        "files": {
            "test.cs": {
                "filename": "test.cs",
                "type": "text/plain",
                "language": "C#",
                "raw_url": "https://gist.githubusercontent.com/octocat/1162032/raw/51eb1d630526c18d123b67637ffcc1e88fb3909b/test.cs",
                "size": 77
            }
        },
        "public": true,
        "created_at": "2011-08-22T09:46:16Z",
        "updated_at": "2021-01-17T17:49:49Z",
        "description": null,
        "comments": 1,
        "user": null,
        "comments_url": "https://api.github.com/gists/1162032/comments",
        "owner": {
            "login": "octocat",
            "id": 583231,
            "node_id": "MDQ6VXNlcjU4MzIzMQ==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "truncated": false
    }
]

const userMock = {
    "login": "octocat",
    "id": 583231,
    "node_id": "MDQ6VXNlcjU4MzIzMQ==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/583231?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false,
    "name": "The Octocat",
    "company": "@github",
    "blog": "https://github.blog",
    "location": "San Francisco",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 8,
    "public_gists": 8,
    "followers": 3467,
    "following": 9,
    "created_at": "2011-01-25T18:44:36Z",
    "updated_at": "2021-01-07T11:51:30Z"
}

const forksMock = [
    {
        "url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533",
        "forks_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/forks",
        "commits_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/commits",
        "id": "fc06f335f39a0addb4f1784afd744533",
        "node_id": "MDQ6R2lzdGZjMDZmMzM1ZjM5YTBhZGRiNGYxNzg0YWZkNzQ0NTMz",
        "git_pull_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533.git",
        "git_push_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533.git",
        "html_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533",
        "files": {},
        "public": true,
        "created_at": "2016-07-28T08:26:56Z",
        "updated_at": "2020-05-22T12:44:36Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/comments",
        "owner": {
            "login": "nlwy",
            "id": 14729172,
            "node_id": "MDQ6VXNlcjE0NzI5MTcy",
            "avatar_url": "https://avatars1.githubusercontent.com/u/14729172?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nlwy",
            "html_url": "https://github.com/nlwy",
            "followers_url": "https://api.github.com/users/nlwy/followers",
            "following_url": "https://api.github.com/users/nlwy/following{/other_user}",
            "gists_url": "https://api.github.com/users/nlwy/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nlwy/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nlwy/subscriptions",
            "organizations_url": "https://api.github.com/users/nlwy/orgs",
            "repos_url": "https://api.github.com/users/nlwy/repos",
            "events_url": "https://api.github.com/users/nlwy/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nlwy/received_events",
            "type": "User",
            "site_admin": false
        }
    },
    {
        "url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3",
        "forks_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/forks",
        "commits_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/commits",
        "id": "34a30ca2ae210c7e8523a312111354d3",
        "node_id": "MDQ6R2lzdDM0YTMwY2EyYWUyMTBjN2U4NTIzYTMxMjExMTM1NGQz",
        "git_pull_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3.git",
        "git_push_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3.git",
        "html_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3",
        "files": {},
        "public": true,
        "created_at": "2017-07-11T10:17:11Z",
        "updated_at": "2017-07-11T10:17:11Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/comments",
        "owner": {
            "login": "sunofsparda",
            "id": 10135454,
            "node_id": "MDQ6VXNlcjEwMTM1NDU0",
            "avatar_url": "https://avatars0.githubusercontent.com/u/10135454?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sunofsparda",
            "html_url": "https://github.com/sunofsparda",
            "followers_url": "https://api.github.com/users/sunofsparda/followers",
            "following_url": "https://api.github.com/users/sunofsparda/following{/other_user}",
            "gists_url": "https://api.github.com/users/sunofsparda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sunofsparda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sunofsparda/subscriptions",
            "organizations_url": "https://api.github.com/users/sunofsparda/orgs",
            "repos_url": "https://api.github.com/users/sunofsparda/repos",
            "events_url": "https://api.github.com/users/sunofsparda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sunofsparda/received_events",
            "type": "User",
            "site_admin": false
        }
    },
    {
        "url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072",
        "forks_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/forks",
        "commits_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/commits",
        "id": "7bf101011045d3c226d2c2707a3b6072",
        "node_id": "MDQ6R2lzdDdiZjEwMTAxMTA0NWQzYzIyNmQyYzI3MDdhM2I2MDcy",
        "git_pull_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072.git",
        "git_push_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072.git",
        "html_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072",
        "files": {},
        "public": true,
        "created_at": "2019-05-26T08:52:00Z",
        "updated_at": "2019-05-26T08:52:01Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/comments",
        "owner": {
            "login": "hannesschulze",
            "id": 43932053,
            "node_id": "MDQ6VXNlcjQzOTMyMDUz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/43932053?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hannesschulze",
            "html_url": "https://github.com/hannesschulze",
            "followers_url": "https://api.github.com/users/hannesschulze/followers",
            "following_url": "https://api.github.com/users/hannesschulze/following{/other_user}",
            "gists_url": "https://api.github.com/users/hannesschulze/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hannesschulze/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hannesschulze/subscriptions",
            "organizations_url": "https://api.github.com/users/hannesschulze/orgs",
            "repos_url": "https://api.github.com/users/hannesschulze/repos",
            "events_url": "https://api.github.com/users/hannesschulze/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hannesschulze/received_events",
            "type": "User",
            "site_admin": false
        }
    },
    {
        "url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533",
        "forks_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/forks",
        "commits_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/commits",
        "id": "fc06f335f39a0addb4f1784afd744533",
        "node_id": "MDQ6R2lzdGZjMDZmMzM1ZjM5YTBhZGRiNGYxNzg0YWZkNzQ0NTMz",
        "git_pull_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533.git",
        "git_push_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533.git",
        "html_url": "https://gist.github.com/fc06f335f39a0addb4f1784afd744533",
        "files": {},
        "public": true,
        "created_at": "2016-07-28T08:26:56Z",
        "updated_at": "2020-05-22T12:44:36Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/fc06f335f39a0addb4f1784afd744533/comments",
        "owner": {
            "login": "nlwy",
            "id": 14729172,
            "node_id": "MDQ6VXNlcjE0NzI5MTcy",
            "avatar_url": "https://avatars1.githubusercontent.com/u/14729172?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nlwy",
            "html_url": "https://github.com/nlwy",
            "followers_url": "https://api.github.com/users/nlwy/followers",
            "following_url": "https://api.github.com/users/nlwy/following{/other_user}",
            "gists_url": "https://api.github.com/users/nlwy/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nlwy/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nlwy/subscriptions",
            "organizations_url": "https://api.github.com/users/nlwy/orgs",
            "repos_url": "https://api.github.com/users/nlwy/repos",
            "events_url": "https://api.github.com/users/nlwy/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nlwy/received_events",
            "type": "User",
            "site_admin": false
        }
    },
    {
        "url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3",
        "forks_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/forks",
        "commits_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/commits",
        "id": "34a30ca2ae210c7e8523a312111354d3",
        "node_id": "MDQ6R2lzdDM0YTMwY2EyYWUyMTBjN2U4NTIzYTMxMjExMTM1NGQz",
        "git_pull_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3.git",
        "git_push_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3.git",
        "html_url": "https://gist.github.com/34a30ca2ae210c7e8523a312111354d3",
        "files": {},
        "public": true,
        "created_at": "2017-07-11T10:17:11Z",
        "updated_at": "2017-07-11T10:17:11Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/34a30ca2ae210c7e8523a312111354d3/comments",
        "owner": {
            "login": "sunofsparda",
            "id": 10135454,
            "node_id": "MDQ6VXNlcjEwMTM1NDU0",
            "avatar_url": "https://avatars0.githubusercontent.com/u/10135454?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sunofsparda",
            "html_url": "https://github.com/sunofsparda",
            "followers_url": "https://api.github.com/users/sunofsparda/followers",
            "following_url": "https://api.github.com/users/sunofsparda/following{/other_user}",
            "gists_url": "https://api.github.com/users/sunofsparda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sunofsparda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sunofsparda/subscriptions",
            "organizations_url": "https://api.github.com/users/sunofsparda/orgs",
            "repos_url": "https://api.github.com/users/sunofsparda/repos",
            "events_url": "https://api.github.com/users/sunofsparda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sunofsparda/received_events",
            "type": "User",
            "site_admin": false
        }
    },
    {
        "url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072",
        "forks_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/forks",
        "commits_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/commits",
        "id": "7bf101011045d3c226d2c2707a3b6072",
        "node_id": "MDQ6R2lzdDdiZjEwMTAxMTA0NWQzYzIyNmQyYzI3MDdhM2I2MDcy",
        "git_pull_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072.git",
        "git_push_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072.git",
        "html_url": "https://gist.github.com/7bf101011045d3c226d2c2707a3b6072",
        "files": {},
        "public": true,
        "created_at": "2019-05-26T08:52:00Z",
        "updated_at": "2019-05-26T08:52:01Z",
        "description": "Hello world!",
        "comments": 0,
        "user": null,
        "comments_url": "https://api.github.com/gists/7bf101011045d3c226d2c2707a3b6072/comments",
        "owner": {
            "login": "hannesschulze",
            "id": 43932053,
            "node_id": "MDQ6VXNlcjQzOTMyMDUz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/43932053?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hannesschulze",
            "html_url": "https://github.com/hannesschulze",
            "followers_url": "https://api.github.com/users/hannesschulze/followers",
            "following_url": "https://api.github.com/users/hannesschulze/following{/other_user}",
            "gists_url": "https://api.github.com/users/hannesschulze/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hannesschulze/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hannesschulze/subscriptions",
            "organizations_url": "https://api.github.com/users/hannesschulze/orgs",
            "repos_url": "https://api.github.com/users/hannesschulze/repos",
            "events_url": "https://api.github.com/users/hannesschulze/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hannesschulze/received_events",
            "type": "User",
            "site_admin": false
        }
    }
]
export {gistsMock,forksMock,userMock}